const PACK_FILES = [
  // ─── KICK ───────────────────────────────────────────────────
  {cat:'KICK',  f:'kick/KICK_DOBE_PUNCH_01.wav',           type:'KICK',    ptype:'kick'},
  {cat:'KICK',  f:'kick/KICK_DOBE_WAREHOUSE_03.wav',       type:'KICK',    ptype:'kick'},
  {cat:'KICK',  f:'kick/KICK_DOBE_PHANTOM_04.wav',         type:'KICK',    ptype:'kick'},
  {cat:'KICK',  f:'kick/KICK_DOBE_LOWZZ_05.wav',           type:'KICK',    ptype:'kick'},
  {cat:'KICK',  f:'kick/KICK_DOBE_AFTERHOURS_06.wav',      type:'KICK',    ptype:'kick'},
  {cat:'KICK',  f:'kick/KICK_DOBE_CONCRETE_07.wav',        type:'KICK',    ptype:'kick'},
  {cat:'KICK',  f:'kick/KICK_DOBE_DRYCLUB_08.wav',         type:'KICK',    ptype:'kick'},
  {cat:'KICK',  f:'kick/KICK_DOBE_SHADOW_09.wav',          type:'KICK',    ptype:'kick'},
  {cat:'KICK',  f:'kick/KICK_DOBE_NEON_10.wav',            type:'KICK',    ptype:'kick'},
  {cat:'KICK',  f:'kick/KICK_DOBE_BUNKER_11.wav',          type:'KICK',    ptype:'kick'},
  {cat:'KICK',  f:'kick/KICK_DOBE_STATIC_12.wav',          type:'KICK',    ptype:'kick'},
  {cat:'KICK',  f:'kick/KICK_DOBE_FACTORY_13.wav',         type:'KICK',    ptype:'kick'},
  {cat:'KICK',  f:'kick/KICK_DOBE_HEAVYLOW_14.aif',        type:'KICK',    ptype:'kick'},
  {cat:'KICK',  f:'kick/KICK_DOBE_CHROME_15.wav',          type:'KICK',    ptype:'kick'},
  {cat:'KICK',  f:'kick/KICK_DOBE_ROLLING_16.wav',         type:'KICK',    ptype:'kick'},
  {cat:'KICK',  f:'kick/KICK_DOBE_DUST_17.aif',            type:'KICK',    ptype:'kick'},
  {cat:'KICK',  f:'kick/KICK_DOBE_TIGHTROOM_18.wav',       type:'KICK',    ptype:'kick'},
  {cat:'KICK',  f:'kick/KICK_DOBE_VELVETSUB_19.wav',       type:'KICK',    ptype:'kick'},
  {cat:'KICK',  f:'kick/KICK_DOBE_NIGHTSHIFT_20.wav',      type:'KICK',    ptype:'kick'},
  // ─── CLAP ───────────────────────────────────────────────────
  {cat:'CLAP',  f:'clap/CLAP_DOBE_SNAP_01.wav',            type:'CLAP',    ptype:'clap'},
  {cat:'CLAP',  f:'clap/CLAP_DOBE_SMACK_02.wav',           type:'CLAP',    ptype:'clap'},
  {cat:'CLAP',  f:'clap/CLAP_DOBE_SLAP_03.wav',            type:'CLAP',    ptype:'clap'},
  {cat:'CLAP',  f:'clap/CLAP_DOBE_CRUNCH_04.wav',          type:'CLAP',    ptype:'clap'},
  {cat:'CLAP',  f:'clap/CLAP_DOBE_POPSHOT_05.wav',         type:'CLAP',    ptype:'clap'},
  {cat:'CLAP',  f:'clap/CLAP_DOBE_DRYFIRE_06.wav',         type:'CLAP',    ptype:'clap'},
  {cat:'CLAP',  f:'clap/CLAP_DOBE_RIMSHOT_07.wav',         type:'CLAP',    ptype:'clap'},
  {cat:'CLAP',  f:'clap/CLAP_DOBE_STADIUM_08.wav',         type:'CLAP',    ptype:'clap'},
  {cat:'CLAP',  f:'clap/CLAP_DOBE_THUD_09.wav',            type:'CLAP',    ptype:'clap'},
  {cat:'CLAP',  f:'clap/CLAP_DOBE_CLACK_10.wav',           type:'CLAP',    ptype:'clap'},
  // ─── HIHAT ──────────────────────────────────────────────────
  {cat:'HIHAT', f:'hihat/HIHAT_DOBE_GLIDE_01.wav',         type:'HIHAT',   ptype:'hihat'},
  {cat:'HIHAT', f:'hihat/HIHAT_DOBE_CRISP_02.wav',         type:'HIHAT',   ptype:'hihat'},
  {cat:'HIHAT', f:'hihat/HIHAT_DOBE_FLICK_03.wav',         type:'HIHAT',   ptype:'hihat'},
  {cat:'HIHAT', f:'hihat/HIHAT_DOBE_RUSH_04.wav',          type:'HIHAT',   ptype:'hihat'},
  {cat:'HIHAT', f:'hihat/HIHAT_DOBE_SPARK_05.wav',         type:'HIHAT',   ptype:'hihat'},
  {cat:'HIHAT', f:'hihat/HIHAT_DOBE_VORTEX_06.wav',        type:'HIHAT',   ptype:'hihat'},
  {cat:'HIHAT', f:'hihat/HIHAT_DOBE_SLICE_07.wav',         type:'HIHAT',   ptype:'hihat'},
  {cat:'HIHAT', f:'hihat/HIHAT_DOBE_GHOST_08.wav',         type:'HIHAT',   ptype:'hihat'},
  {cat:'HIHAT', f:'hihat/HIHAT_DOBE_AIRFLOW_09.wav',       type:'HIHAT',   ptype:'hihat'},
  {cat:'HIHAT', f:'hihat/HIHAT_DOBE_VOLT_10.wav',          type:'HIHAT',   ptype:'hihat'},
  {cat:'HIHAT', f:'hihat/HIHAT_DOBE_FUSION_11.wav',        type:'HIHAT',   ptype:'hihat'},
  {cat:'HIHAT', f:'hihat/HIHAT_DOBE_DRIFT_12.aif',         type:'HIHAT',   ptype:'hihat'},
  {cat:'HIHAT', f:'hihat/HIHAT_DOBE_PIXELS_13.wav',        type:'HIHAT',   ptype:'hihat'},
  {cat:'HIHAT', f:'hihat/HIHAT_DOBE_FLUX_14.wav',          type:'HIHAT',   ptype:'hihat'},
  {cat:'HIHAT', f:'hihat/HIHAT_DOBE_LIQUID_15.wav',        type:'HIHAT',   ptype:'hihat'},
  {cat:'HIHAT', f:'hihat/HIHAT_DOBE_SIGNAL_16.wav',        type:'HIHAT',   ptype:'hihat'},
  {cat:'HIHAT', f:'hihat/HIHAT_DOBE_ICECUT_17.wav',        type:'HIHAT',   ptype:'hihat'},
  {cat:'HIHAT', f:'hihat/HIHAT_DOBE_BLINK_18.wav',         type:'HIHAT',   ptype:'hihat'},
  {cat:'HIHAT', f:'hihat/HIHAT_DOBE_WIREFRAME_19.wav',     type:'HIHAT',   ptype:'hihat'},
  {cat:'HIHAT', f:'hihat/HIHAT_DOBE_FASTLANE_20.wav',      type:'HIHAT',   ptype:'hihat'},
  // ─── SNARE ──────────────────────────────────────────────────
  {cat:'SNARE', f:'snare/SNARE_DOBE_CRACK_01.wav',         type:'SNARE',   ptype:'snare'},
  {cat:'SNARE', f:'snare/SNARE_DOBE_DIRTY_02.wav',         type:'SNARE',   ptype:'snare'},
  {cat:'SNARE', f:'snare/SNARE_DOBE_TIGHT_03.wav',         type:'SNARE',   ptype:'snare'},
  {cat:'SNARE', f:'snare/SNARE_DOBE_CLAPSNAP_04.wav',      type:'SNARE',   ptype:'snare'},
  {cat:'SNARE', f:'snare/SNARE_DOBE_METAL_05.wav',         type:'SNARE',   ptype:'snare'},
  {cat:'SNARE', f:'snare/SNARE_DOBE_PHANTOM_06.wav',       type:'SNARE',   ptype:'snare'},
  {cat:'SNARE', f:'snare/SNARE_DOBE_DRYHIT_07.wav',        type:'SNARE',   ptype:'snare'},
  {cat:'SNARE', f:'snare/SNARE_DOBE_SHADOW_08.wav',        type:'SNARE',   ptype:'snare'},
  {cat:'SNARE', f:'snare/SNARE_DOBE_CONCRETE_09.wav',      type:'SNARE',   ptype:'snare'},
  {cat:'SNARE', f:'snare/SNARE_DOBE_NEON_10.wav',          type:'SNARE',   ptype:'snare'},
  {cat:'SNARE', f:'snare/SNARE_DOBE_STATIC_11.wav',        type:'SNARE',   ptype:'snare'},
  {cat:'SNARE', f:'snare/SNARE_DOBE_AFTER_12.wav',         type:'SNARE',   ptype:'snare'},
  {cat:'SNARE', f:'snare/SNARE_DOBE_CHROME_13.wav',        type:'SNARE',   ptype:'snare'},
  {cat:'SNARE', f:'snare/SNARE_DOBE_PUNCHLINE_14.wav',     type:'SNARE',   ptype:'snare'},
  {cat:'SNARE', f:'snare/SNARE_DOBE_FACTORY_15.wav',       type:'SNARE',   ptype:'snare'},
  {cat:'SNARE', f:'snare/SNARE_DOBE_VELVET_16.wav',        type:'SNARE',   ptype:'snare'},
  {cat:'SNARE', f:'snare/SNARE_DOBE_BUNKER_17.wav',        type:'SNARE',   ptype:'snare'},
  {cat:'SNARE', f:'snare/SNARE_DOBE_DUST_18.wav',          type:'SNARE',   ptype:'snare'},
  {cat:'SNARE', f:'snare/SNARE_DOBE_ROLLER_19.aif',        type:'SNARE',   ptype:'snare'},
  {cat:'SNARE', f:'snare/SNARE_DOBE_NIGHTSHIFT_20.aif',    type:'SNARE',   ptype:'snare'},
  // ─── TOP LOOPS ──────────────────────────────────────────────
  {cat:'LOOP',  f:'loops/TOPLOOP_DOBE_GROOVELINE_01.wav',  type:'LOOP',    ptype:'loop'},
  {cat:'LOOP',  f:'loops/TOPLOOP_DOBE_AFTERDARK_02.mp3',   type:'LOOP',    ptype:'loop'},
  {cat:'LOOP',  f:'loops/TOPLOOP_DOBE_VIBEDRIFT_03.wav',   type:'LOOP',    ptype:'loop'},
  {cat:'LOOP',  f:'loops/TOPLOOP_DOBE_RHYTHMWAVE_04.wav',  type:'LOOP',    ptype:'loop'},
  {cat:'LOOP',  f:'loops/TOPLOOP_DOBE_CIRCUIT_05.wav',     type:'LOOP',    ptype:'loop'},
  {cat:'LOOP',  f:'loops/TOPLOOP_DOBE_MOTION_06.wav',      type:'LOOP',    ptype:'loop'},
  {cat:'LOOP',  f:'loops/TOPLOOP_DOBE_SKYLINE_07.wav',     type:'LOOP',    ptype:'loop'},
  {cat:'LOOP',  f:'loops/TOPLOOP_DOBE_FLOWSTATE_08.wav',   type:'LOOP',    ptype:'loop'},
  {cat:'LOOP',  f:'loops/TOPLOOP_DOBE_VELCRO_09.wav',      type:'LOOP',    ptype:'loop'},
  {cat:'LOOP',  f:'loops/TOPLOOP_DOBE_CLOCKWORK_10.wav',   type:'LOOP',    ptype:'loop'},
  {cat:'LOOP',  f:'loops/TOPLOOP_DOBE_FREQUENCY_11.wav',   type:'LOOP',    ptype:'loop'},
  {cat:'LOOP',  f:'loops/TOPLOOP_DOBE_PULSEGRID_12.wav',   type:'LOOP',    ptype:'loop'},
  {cat:'LOOP',  f:'loops/TOPLOOP_DOBE_MIDNIGHT_13.wav',    type:'LOOP',    ptype:'loop'},
  {cat:'LOOP',  f:'loops/TOPLOOP_DOBE_TRANSIT_14.wav',     type:'LOOP',    ptype:'loop'},
  {cat:'LOOP',  f:'loops/TOPLOOP_DOBE_STREETSYNC_15.wav',  type:'LOOP',    ptype:'loop'},
  {cat:'LOOP',  f:'loops/TOPLOOP_DOBE_CYBERMOVE_16.wav',   type:'LOOP',    ptype:'loop'},
  {cat:'LOOP',  f:'loops/TOPLOOP_DOBE_BASSDISTRICT_17.wav',type:'LOOP',    ptype:'loop'},
  {cat:'LOOP',  f:'loops/TOPLOOP_DOBE_NEXUS_18.wav',       type:'LOOP',    ptype:'loop'},
  {cat:'LOOP',  f:'loops/TOPLOOP_DOBE_HEATZONE_19.wav',    type:'LOOP',    ptype:'loop'},
  {cat:'LOOP',  f:'loops/TOPLOOP_DOBE_OVERCLOCK_20.aif',   type:'LOOP',    ptype:'loop'},
  // ─── FX · UPLIFTERS ─────────────────────────────────────────
  {cat:'FX',    f:'fx/UPLIFT_DOBE_ASCEND_01.wav',          type:'UPLIFT',  ptype:'fx · uplift'},
  {cat:'FX',    f:'fx/UPLIFT_DOBE_LAUNCH_02.wav',          type:'UPLIFT',  ptype:'fx · uplift'},
  {cat:'FX',    f:'fx/UPLIFT_DOBE_SURGE_03.wav',           type:'UPLIFT',  ptype:'fx · uplift'},
  {cat:'FX',    f:'fx/UPLIFT_DOBE_LIFTOFF_04.wav',         type:'UPLIFT',  ptype:'fx · uplift'},
  {cat:'FX',    f:'fx/UPLIFT_DOBE_ELEVATE_05.wav',         type:'UPLIFT',  ptype:'fx · uplift'},
  {cat:'FX',    f:'fx/UPLIFT_DOBE_BOOST_06.wav',           type:'UPLIFT',  ptype:'fx · uplift'},
  {cat:'FX',    f:'fx/UPLIFT_DOBE_THRUST_07.wav',          type:'UPLIFT',  ptype:'fx · uplift'},
  {cat:'FX',    f:'fx/UPLIFT_DOBE_CLIMB_08.wav',           type:'UPLIFT',  ptype:'fx · uplift'},
  {cat:'FX',    f:'fx/UPLIFT_DOBE_APEX_09.wav',            type:'UPLIFT',  ptype:'fx · uplift'},
  {cat:'FX',    f:'fx/UPLIFT_DOBE_ZENITH_10.wav',          type:'UPLIFT',  ptype:'fx · uplift'},
  // ─── FX · AMBIENCE ──────────────────────────────────────────
  {cat:'FX',    f:'fx/AMBIENCE_DOBE_LOUNGE_01.wav',        type:'AMBIENCE',ptype:'fx · ambience'},
  {cat:'FX',    f:'fx/AMBIENCE_DOBE_METROPOLIS_02.wav',    type:'AMBIENCE',ptype:'fx · ambience'},
  {cat:'FX',    f:'fx/AMBIENCE_DOBE_WOODLAND_03.wav',      type:'AMBIENCE',ptype:'fx · ambience'},
  {cat:'FX',    f:'fx/AMBIENCE_DOBE_DOWNPOUR_04.wav',      type:'AMBIENCE',ptype:'fx · ambience'},
  {cat:'FX',    f:'fx/AMBIENCE_DOBE_CANTEEN_05.wav',       type:'AMBIENCE',ptype:'fx · ambience'},
  {cat:'FX',    f:'fx/AMBIENCE_DOBE_ARCO_06.wav',          type:'AMBIENCE',ptype:'fx · ambience'},
  {cat:'FX',    f:'fx/AMBIENCE_DOBE_WAXDUST_07.wav',       type:'AMBIENCE',ptype:'fx · ambience'},
  {cat:'FX',    f:'fx/AMBIENCE_DOBE_TAPEWARM_08.wav',      type:'AMBIENCE',ptype:'fx · ambience'},
  {cat:'FX',    f:'fx/AMBIENCE_DOBE_GRAINFIELD_09.wav',    type:'AMBIENCE',ptype:'fx · ambience'},
  // ─── FX · DOWNLIFTERS ───────────────────────────────────────
  {cat:'FX',    f:'fx/DOWN_DOBE_DESCENT_01.wav',           type:'DOWN',    ptype:'fx · down'},
  {cat:'FX',    f:'fx/DOWN_DOBE_COLLAPSE_02.wav',          type:'DOWN',    ptype:'fx · down'},
  {cat:'FX',    f:'fx/DOWN_DOBE_FALLOUT_03.wav',           type:'DOWN',    ptype:'fx · down'},
  {cat:'FX',    f:'fx/DOWN_DOBE_DROPTONE_04.wav',          type:'DOWN',    ptype:'fx · down'},
  {cat:'FX',    f:'fx/DOWN_DOBE_PLUNGE_05.wav',            type:'DOWN',    ptype:'fx · down'},
  {cat:'FX',    f:'fx/DOWN_DOBE_GRAVITY_06.wav',           type:'DOWN',    ptype:'fx · down'},
  {cat:'FX',    f:'fx/DOWN_DOBE_SINKWAVE_07.wav',          type:'DOWN',    ptype:'fx · down'},
  {cat:'FX',    f:'fx/DOWN_DOBE_DECLINE_08.wav',           type:'DOWN',    ptype:'fx · down'},
  {cat:'FX',    f:'fx/DOWN_DOBE_FREEFALL_09.wav',          type:'DOWN',    ptype:'fx · down'},
  {cat:'FX',    f:'fx/DOWN_DOBE_BLACKOUT_10.wav',          type:'DOWN',    ptype:'fx · down'},
  // ─── FX · IMPACTS ───────────────────────────────────────────
  {cat:'FX',    f:'fx/FX_DOBE_REBOUND_01.wav',             type:'IMPACT',  ptype:'fx · impact'},
  {cat:'FX',    f:'fx/IMPACT_DOBE_SHOCKWAVE_01.wav',       type:'IMPACT',  ptype:'fx · impact'},
  {cat:'FX',    f:'fx/IMPACT_DOBE_TREMOR_02.wav',          type:'IMPACT',  ptype:'fx · impact'},
  {cat:'FX',    f:'fx/IMPACT_DOBE_BLAST_03.wav',           type:'IMPACT',  ptype:'fx · impact'},
  {cat:'FX',    f:'fx/IMPACT_DOBE_COLLISION_04.wav',       type:'IMPACT',  ptype:'fx · impact'},
  {cat:'FX',    f:'fx/IMPACT_DOBE_DETONATION_05.wav',      type:'IMPACT',  ptype:'fx · impact'},
  {cat:'FX',    f:'fx/IMPACT_DOBE_RUMBLE_06.wav',          type:'IMPACT',  ptype:'fx · impact'},
  {cat:'FX',    f:'fx/IMPACT_DOBE_STRIKE_07.wav',          type:'IMPACT',  ptype:'fx · impact'},
  {cat:'FX',    f:'fx/IMPACT_DOBE_QUAKE_08.wav',           type:'IMPACT',  ptype:'fx · impact'},
  {cat:'FX',    f:'fx/IMPACT_DOBE_BOOM_09.wav',            type:'IMPACT',  ptype:'fx · impact'},
  {cat:'FX',    f:'fx/IMPACT_DOBE_FRACTURE_10.wav',        type:'IMPACT',  ptype:'fx · impact'},
  // ─── FX · MISC ──────────────────────────────────────────────
  {cat:'FX',    f:'fx/FX_DOBE_GLITCH_01.wav',              type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_FOAM_02.wav',                type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_CHURN_03.wav',               type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_JITTER_04.wav',              type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_LASERDISC_05.wav',           type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_PRISM_06.wav',               type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_VERTIGO_07.wav',             type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_GAMEOVER_08.wav',            type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_ZAPPER_09.wav',              type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_RAYGUN_10.wav',              type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_PROTON_11.wav',              type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_ZEPHYR_12.wav',              type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_WAVEFORM_13.wav',            type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_STROBE_14.wav',              type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_PULSAR_15.wav',              type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_WHITEHEAT_16.wav',           type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_STONEDROP_17.wav',           type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_PEW_18.wav',                 type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_PHASER_19.wav',              type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_STAIRWAY_20.wav',            type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_ORBIT_21.wav',               type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_UPSHOT_22.wav',              type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_SNOWFALL_23.wav',            type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_BLIZZARD_24.wav',            type:'FX',      ptype:'fx · misc'},
  {cat:'FX',    f:'fx/FX_DOBE_FLUTTER_25.wav',             type:'FX',      ptype:'fx · misc'},
  // ─── BONUS ──────────────────────────────────────────────────
  {cat:'BONUS', f:'bonus/DOBÊ - BEST HAT 808.wav',         type:'BONUS',   ptype:'bonus'},
  {cat:'BONUS', f:'bonus/DOBÊ - CLOSED HAT  (Dminor).wav', type:'BONUS',   ptype:'bonus'},
  {cat:'BONUS', f:'bonus/DOBÊ - DRUM LOOP.wav',            type:'BONUS',   ptype:'bonus'},
  {cat:'BONUS', f:'bonus/DOBÊ - FILL.wav',                 type:'BONUS',   ptype:'bonus'},
  {cat:'BONUS', f:'bonus/DOBÊ - HAT 808 (Cminor).wav',    type:'BONUS',   ptype:'bonus'},
  {cat:'BONUS', f:'bonus/DOBÊ - OPEN HAT (STEREO).wav',   type:'BONUS',   ptype:'bonus'},
  {cat:'BONUS', f:'bonus/DOBÊ - TOP LOOP (123Bbpm).wav',  type:'BONUS',   ptype:'bonus'},
];
